sudo: false
language: ruby
rvm:
- 2.2

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - PROJECT_ID=updaterocker
  - SRV_ACCOUNT=439900835842-962b8icmhgpo018ksse9g73mamn8ah45@developer.gserviceaccount.com

script: 
  - bundle exec jekyll build

before_install:
  - git submodule update --init --recursive

after_success:
 - openssl aes-256-cbc -K $encrypted_aa3d0e51e50d_key -iv $encrypted_aa3d0e51e50d_iv -in $PROJECT_ID.json.enc -out $PROJECT_ID.json -d
 - curl https://sdk.cloud.google.com | bash
 - $HOME/google-cloud-sdk/bin/gcloud components update app -q
 - $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account $SRV_ACCOUNT --key-file $PROJECT_ID.json
 - $HOME/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
 - $HOME/google-cloud-sdk/bin/gcloud preview app modules cancel-deployment default --version $TRAVIS_BRANCH
 - $HOME/google-cloud-sdk/bin/gcloud --verbosity info preview app deploy --version $TRAVIS_BRANCH ./app.yaml

# branch whitelist
branches:
  only:
  - master     # test the master branch
  - development
