language: ruby
rvm:
- 2.2
# script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master     # test the master branch
  - development

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
