# Site settings
title: HtML5 Rocks - Chrome updates
description: >
  "Html5 Rocks updates stream."
baseurl: ""
# TODO: change link.
url: "http://devnook.github.io/updates.html5rocks.com.new"
markdown: kramdown
permalink: /:year/:month/:title

highlighter: pygments
include: [samples]
