# Site settings
title: HtML5 Rocks - Chrome updates
description: >
  "Html5 Rocks updates stream."
baseurl: ""
# TODO: change link.
url: ""
# url: "http://localhost:8080"
#url: "http://devnook.github.io/updates.html5rocks.com.new"
html5rocks_url: "http://www.html5rocks.com"
markdown: kramdown
permalink: /:year/:month/:title

highlighter: pygments
paginate: 6
paginate_path: "/page/:num"

include: [samples]

gems: [jekyll-assets]
assets:
  js_compressor:  uglifier
  css_compressor: sass
  # TODO: change link.
  baseurl: /assets/
  #baseurl: http://devnook.github.io/updates.html5rocks.com.new/assets/
  gzip: [ text/css, application/javascript ]
