# Site settings
title: "HTML5 Rocks - Chrome updates"
description: "HTML5Rocks updates stream."
baseurl: ""
url: "http://updates.html5rocks.com"
html5rocks_url: "http://www.html5rocks.com"
markdown: kramdown
permalink: /:year/:month/:title

highlighter: pygments
paginate: 10
paginate_path: "/page/:num"

include: [samples]
exclude: [ "app.yaml", "README.md", vendor ]

gems: [jekyll-assets]
assets:
  js_compressor:  uglifier
  css_compressor: sass
  # TODO: change link.
  baseurl: /assets/
  #baseurl: http://devnook.github.io/updates.html5rocks.com.new/assets/
  gzip: [ text/css, application/javascript ]
