application: updaterocker
version: 20140930
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /json
  mime_type: application/json
  static_files: _site/index.json
  upload: _site/index.json

- url: /assets/(.+)
  static_files: _site/assets/\1
  upload: _site/assets/(.+)

- url: /(\d+)/(\d+)/(.+)
  mime_type: text/html
  static_files: _site/\1/\2/\3/index.html
  upload: _site/(.+)

- url: /page/1
  mime_type: text/html
  static_files: _site/index.html
  upload: _site/index.html


- url: /(\w+)/(\w+)
  mime_type: text/html
  static_files: _site/\1/\2/index.html
  upload: _site/(.+)



- url: /
  mime_type: text/html
  static_files: _site/index.html
  upload: _site/index.html

- url: /.*
  mime_type: text/html
  static_files: _site/404.html
  upload: _site/404.html
