application: updaterocker
version: 20140930
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /json
  mime_type: application/json
  static_files: _site/index.json
  upload: _site/index.json
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /manifest.json
  mime_type: application/json
  static_files: _site/manifest.json
  upload: _site/manifest.json
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /rss
  static_files: _site/feed.xml
  upload: _site/feed.xml
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /assets/(.+)
  static_files: _site/assets/\1
  upload: _site/assets/(.+)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /samples/styles/(.+)
  static_files: _site/samples/styles/\1
  upload: _site/(.+)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /samples/(\w+)/(.+)
  mime_type: text/html
  static_files: _site/samples/\1/index.html
  upload: _site/(.+)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(\d+)/(\d+)/(.+)
  mime_type: text/html
  static_files: _site/\1/\2/\3/index.html
  upload: _site/(.+)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /page/1
  mime_type: text/html
  static_files: _site/index.html
  upload: _site/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(\w+)/(\w+)
  mime_type: text/html
  static_files: _site/\1/\2/index.html
  upload: _site/(.+)
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /
  mime_type: text/html
  static_files: _site/index.html
  upload: _site/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  mime_type: text/html
  static_files: _site/404.html
  upload: _site/404.html
