application: devnook-playground
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets/(.+)
  static_files: _site/assets/\1
  upload: _site/assets/(.+)

- url: /(\d+)/(\d+)/(.+)
  mime_type: text/html
  static_files: _site/\1/\2/\3/index.html
  upload: _site/(.+)

- url: /
  mime_type: text/html
  static_files: _site/index.html
  upload: _site/index.html

- url: /.*
  mime_type: text/html
  static_files: _site/404.html
  upload: _site/404.html
