application: updaterocker
#version: 20140930
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /json
  mime_type: application/json
  static_files: _site/index.json
  upload: _site/index.json
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(.*)
  script: main.app


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?vendor/.*$
- ^(.*/)?_posts/.*$
- ^(.*/)?_site/.*\.md$
